service: openimagegenius-frontend

plugins:
  - serverless-s3-sync

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1

custom:
  bucketName: ${self:provider.stage}.auth.openimagegenius.com
  webAppBucketName: ${self:provider.stage}.app.openimagegenius.com
  s3Sync:
    # An example of possible configuration options
    - bucketName: ${self:custom.bucketName}
      localDir: ./website
      deleteRemoved: true # optional, indicates whether sync deletes files no longer present in localDir. Defaults to 'true'
      followSymlinks: true # optional
      defaultContentType: text/html # optional
      params: # optional
        - index.html:
            CacheControl: "no-cache"
        - "*.js":
            CacheControl: "public, max-age=31536000"
      bucketTags:
        stage: ${self:provider.stage}

    - bucketName: ${self:custom.webAppBucketName}
      localDir: ./web-app/build
      deleteRemoved: true # optional, indicates whether sync deletes files no longer present in localDir. Defaults to 'true'
      followSymlinks: true # optional
      defaultContentType: text/html # optional
      params: # optional
        - index.html:
            CacheControl: "no-cache"
        - "*.js":
            CacheControl: "public, max-age=31536000"
      bucketTags:
        stage: ${self:provider.stage}

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html

    WebAppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.webAppBucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
