service: openimagegenius-websockets-api

frameworkVersion: "3"

package:
  patterns:
    - "!manual_dist"
    - "!node_modules/**"
    - "!ws-client"
    - "!ws-server"
    - "!.ws_secret_pass"
    - "!.serverless"
    - "!.gitignore"
    - "!package.json"
    - "!package-lock.json"
    - "!test_requirements.txt"
    - "!pytest.ini"
    - "test_ws_server.py"
    - "!.requirements.zip"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1
  websocketsApiName: openimage-websockets-api-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Serverless Websockets for Using Facing API
  environment:
    # Tables
    USER_TABLE_NAME: ${self:custom.databaseInfo.userTableName}
    REQUEST_TABLE_NAME: ${self:custom.databaseInfo.requestTableName}
    API_TOKEN_TABLE_NAME: ${self:custom.databaseInfo.APITokenTable}
    CONNECTION_TABLE_NAME: ${self:custom.databaseInfo.connectionTableName}
    # Indices
    GOOGLE_USER_ID_INDEX_NAME: ${self:custom.databaseInfo.googleUserIdIndexName}
    USER_GOOGLE_EMAIL_INDEX_NAME: ${self:custom.databaseInfo.userGoogleEmailIndexName}
    REQUEST_UNIQUE_USER_ID_INDEX: ${self:custom.databaseInfo.requestUniqueUserIdIndex}
    API_TOKEN_UNIQUE_USER_ID_INDEX: ${self:custom.databaseInfo.APITokenUniqueUserIdIndex}
    CONNECTION_UNIQUE_USER_ID_INDEX: ${self:custom.databaseInfo.connectionUniqueUserIdIndex}
    # Others
    SQS_REQUEST_URL: ${self:custom.imageProcessingQueueUrl}
    AUTHORIZER_STAGE: ${self:provider.stage}
    API_ID: qwd67w7upb
    GOOGLE_OAUTH_APP_ID: ${self:custom.googleOAuthAppID}
    DEVELOPER_GOOGLE_USER_ID: ${ssm:/dev/develop-google-user-id} # Only exists in dev stage
    WS_SECRET_PASS: ${ssm:/dev/websockets-api/admin-creds} # Only exists in dev stage
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:UpdateItem"
            - "dynamodb:ListStreams"
            - "dynamodb:DescribeTable"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.requestTableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.requestTableName}/index/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.userTableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.userTableName}/index/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.connectionTableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.connectionTableName}/index/*"
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
          Resource:
            - "arn:aws:sqs:${self:provider.region}:*:${self:custom.imageProcessingQueueName}"

functions:
  connectionHandler:
    handler: event_handlers.connection
    events:
      - websocket:
          route: $connect
    layers:
      - Ref: PythonRequirementsLambdaLayer

  authorizationHandler:
    handler: event_handlers.authorization
    events:
      - websocket:
          route: authorize
          routeResponseSelectionExpression: $default
    layers:
      - Ref: PythonRequirementsLambdaLayer

  defaultHandler:
    handler: event_handlers.default
    events:
      - websocket: $default #simple event definition without extra route property
    layers:
      - Ref: PythonRequirementsLambdaLayer

  requestHandler:
    handler: event_handlers.request
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - websocket:
          route: request
          routeResponseSelectionExpression: $default

  databaseUpdateHandler:
    handler: event_handlers.update
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - stream:
          type: dynamodb
          arn: ${cf:openimagegenius-database-dev.RequestTableStreamArn}
          batchSize: 1
          filterPatterns:
            - eventName: [MODIFY]
              dynamodb:
                NewImage:
                  request_status:
                    S: [completed]
            - eventName: [MODIFY]
              dynamodb:
                NewImage:
                  request_status:
                    S: [failed]
plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  imageProcessingQueueName: image-processing-${self:provider.stage}
  imageProcessingQueueUrl: !Ref ImageProcessingQueue
  customDomain:
    domainName: ${self:provider.stage}.ws-api.openimagegenius.com
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: websocket
  pythonRequirements:
    zip: true
    layer: true
    usePipenv: false
  databaseInfo: ${file(../database/serverless.yml):custom}
  OAuthAppIDMapping:
    dev: ${ssm:/dev/google-oauth-app-id}
  googleOAuthAppID: ${self:custom.OAuthAppIDMapping.${self:provider.stage}}

resources:
  Resources:
    ImageProcessingQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        DelaySeconds: 0
        QueueName: image-processing-dead-letter-queue-${self:provider.stage}
        VisibilityTimeout: 30

    ImageProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        DelaySeconds: 0
        QueueName: ${self:custom.imageProcessingQueueName}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ImageProcessingQueueDLQ.Arn
          maxReceiveCount: 3
        VisibilityTimeout: 30

  Outputs:
    ImageProcessingQueue:
      Export:
        Name: image-processing-queue-${self:provider.stage}-arn
      Value:
        Fn::GetAtt: ImageProcessingQueue.Arn
