service: openimagegenius-websockets-api
frameworkVersion: "3"

package:
  patterns:
    - "!manual_dist"
    - "!node_modules/**"
    - "!ws-client"
    - "!ws-server"
    - "!.ws_secret_pass"
    - "!.serverless"
    - "!.gitignore"
    - "!package.json"
    - "!package-lock.json"
    - "!test_requirements.txt"
    - "!pytest.ini"
    - "test_ws_server.py"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1
  websocketsApiName: openimage-websockets-api-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Serverless Websockets for Using Facing API
  environment:
    SQS_REQUEST_URL: ${self:custom.imageProcessingQueueUrl}
    USER_TABLE_NAME: ${self:custom.databaseInfo.userTableName}
    REQUEST_TABLE_NAME: ${self:custom.databaseInfo.requestTableName}
    GOOGLE_USER_ID_INDEX_NAME: ${self:custom.databaseInfo.googleUserIdIndexName}
    USER_GOOGLE_EMAIL_INDEX_NAME: ${self:custom.databaseInfo.userGoogleEmailIndexName}
    REQUEST_UNIQUE_USER_ID_INDEX: ${self:custom.databaseInfo.requestUniqueUserIdIndex}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.requestTableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.requestTableName}/index/*"
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
          Resource:
            - "arn:aws:sqs:${self:provider.region}:*:queue/${self:custom.imageProcessingQueueName}"

functions:
  connectionHandler:
    handler: event_handlers.connection
    events:
      - websocket: 
          route: $connect
          authorizer:
            arn: ${self:custom.authorizerArn}
            identitySource:
              - 'route.request.header.Authorization'
    layers:
      - Ref: PythonRequirementsLambdaLayer


  defaultHandler:
    handler: event_handlers.default
    events:
      - websocket: $default #simple event definition without extra route property
    layers:
      - Ref: PythonRequirementsLambdaLayer
	
  requestHandler:
    handler: event_handlers.request
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - websocket:
          route: request
          routeResponseSelectionExpression: $default

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  authorizerArn: ${cf:openimagegenius-auth-dev.AuthorizerLambdaFunction}
  imageProcessingQueueName: image-processing-${self:provider.stage}.fifo
  imageProcessingQueueUrl: !Ref ImageProcessingQueue
  customDomain:
    domainName: ${self:provider.stage}.ws-api.openimagegenius.com
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: websocket
  pythonRequirements:
    zip: true
    layer: true
    usePipenv: false
  databaseInfo: ${file(../database/serverless.yml):custom}

resources:
  Resources:
    ImageProcessingQueueDLQ:
      Type: AWS::SQS::Queue
      Properties: 
        ContentBasedDeduplication: false
        DelaySeconds: 0
        FifoQueue: true
        QueueName: image-processing-dead-letter-queue-${self:provider.stage}.fifo
        VisibilityTimeout: 30

    ImageProcessingQueue:
      Type: AWS::SQS::Queue
      Properties: 
        ContentBasedDeduplication: false
        DelaySeconds: 0
        FifoQueue: true
        QueueName: ${self:custom.imageProcessingQueueName}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ImageProcessingQueueDLQ.Arn
          maxReceiveCount: 3
        VisibilityTimeout: 30
