service: stable-diffusion-open-vino

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1
  memorySize: 10240

functions:
  text2img:
    url: true
    image: 787492735804.dkr.ecr.eu-central-1.amazonaws.com/cpu-sd-private@sha256:3652cfe1beb826a2675b0739785e905c53828118d43db29f0f02dd833bf53a64
    timeout: 900
