service: stable-diffusion-open-vino

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1
  memorySize: 10240
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:GetObject"
          Resource:
            - "arn:aws:s3:::open-image-genius-open-vino-models/*"
functions:
  text2img:
    url: true
    image:
      name: appimage
    timeout: 900
    environment:
      S3_BUCKET: open-image-genius-open-vino-models