service: stable-diffusion-open-vino

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1
  memorySize: 10240
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::${self:custom.generatedImagesBucket}/*"
        - Effect: Allow
          Action:
            - "elasticfilesystem:*"
          Resource:
            - "arn:aws:elasticfilesystem:${aws:region}:${aws:accountId}:file-system/${self:custom.fileSystemId}"
            - "arn:aws:elasticfilesystem:${aws:region}:${aws:accountId}:access-point/${self:custom.efsAccessPoint}"

functions:
  textToImg:
    image:
      name: appimage
    timeout: 300
    environment:
      S3_BUCKET: ${self:custom.generatedImagesBucket}
      MNT_DIR: ${self:custom.LocalMountPath}
    vpc:
      securityGroupIds:
        - ${self:custom.securityGroup}
      subnetIds:
        - ${self:custom.subnetsId.subnet0}
    events:
      - sqs:
          arn: ${cf:openimagegenius-websockets-api-${self:provider.stage}.ImageCPUProcessingQueue}
          batchSize: 1

custom:
  efsAccessPoint: fsap-00b771e6beaba72c1
  fileSystemId: fs-0dfb0e1ab26ff529f
  LocalMountPath: /mnt/fs
  subnetsId:
    subnet0: subnet-02516fd8fdb201a49
  securityGroup: sg-088dad5e11062b97d
  generatedImagesBucket: ${cf:openimagegenius-image-buckets-${self:provider.stage}.GeneratedImagesBucket}

resources:
  extensions:
    TextToImgLambdaFunction:
      Properties:
        FileSystemConfigs:
          - Arn: "arn:aws:elasticfilesystem:${self:provider.region}:${aws:accountId}:access-point/${self:custom.efsAccessPoint}"
            LocalMountPath: "${self:custom.LocalMountPath}"
