service: openimagegenius-gpu-websockets
frameworkVersion: "3"

package:
  patterns:
    - "!manual_dist"
    - "!node_modules/**"
    - "!ws-client"
    - "!ws-server"
    - "!.ws_secret_pass"
    - "!.serverless"
    - "!.gitignore"
    - "!package.json"
    - "!package-lock.json"
    - "!test_requirements.txt"
    - "!pytest.ini"
    - "test_ws_server.py"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1
  websocketsApiName: openimage-websockets-api-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Serverless Websockets for Using Facing API
  environment:
    # Tables
    USER_TABLE_NAME: ${self:custom.databaseInfo.userTableName}
    REQUEST_TABLE_NAME: ${self:custom.databaseInfo.requestTableName}
    API_TOKEN_TABLE_NAME: ${self:custom.databaseInfo.APITokenTable}
    # Indices
    GOOGLE_USER_ID_INDEX_NAME: ${self:custom.databaseInfo.googleUserIdIndexName}
    USER_GOOGLE_EMAIL_INDEX_NAME: ${self:custom.databaseInfo.userGoogleEmailIndexName}
    REQUEST_UNIQUE_USER_ID_INDEX: ${self:custom.databaseInfo.requestUniqueUserIdIndex}
    API_TOKEN_UNIQUE_USER_ID_INDEX: ${self:custom.databaseInfo.APITokenUniqueUserIdIndex}
    # Others
    AUTHORIZER_STAGE: ${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.APITokenTable}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.databaseInfo.APITokenTable}/index/*"

functions:
  connectionHandler:
    handler: event_handlers.connection
    events:
      - websocket: 
          route: $connect
          authorizer:
            arn: ${self:custom.authorizerArn}
            identitySource:
              - 'route.request.header.api-key'
    layers:
      - Ref: PythonRequirementsLambdaLayer

  GPUAuthorizer:
    handler: gpu_node_authorizer.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer

  defaultHandler:
    handler: event_handlers.default
    events:
      - websocket: $default #simple event definition without extra route property
    layers:
      - Ref: PythonRequirementsLambdaLayer


plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  authorizerArn: ${cf:openimagegenius-auth-dev.AuthorizerLambdaFunction}
  imageProcessingQueueName: image-processing-${self:provider.stage}
  imageProcessingQueueUrl: !Ref ImageProcessingQueue
  customDomain:
    domainName: ${self:provider.stage}.ws-gpus.openimagegenius.com
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: websocket
  pythonRequirements:
    zip: true
    layer: true
    usePipenv: false
  databaseInfo: ${file(../database/serverless.yml):custom}
